defaults: &defaults
    docker:
        - image: circleci/node:8.10.0
    working_directory: ~/tmp/circlci-now

version: 2
jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: ~/tmp/circlci-now
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                  - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --frozen-lockfile
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                  - ~/.cache/yarn
            - persist_to_workspace:
                root: .
                paths: .
    unit-test:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/tmp/circlci-now
            - run:
                name: yarn Install
                command: yarn install
            - run:
                name: Unit Test
                command: yarn run test
            - run:
                name: tsformat
                command: yarn run verify-tsfmt
    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/tmp/circlci-now
            - run:
                name: Install Now CLI
                command: sudo yarn global add now now-serve
            - deploy:
                name: Deploy & Alias
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        ./.now/now.master.sh
                        now --public --token $ZEIT_TOKEN --local-config .now/now.master.json
                        now --token $ZEIT_TOKEN --local-config .now/now.master.json alias
                    elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
                        ./.now/now.dev.sh
                        now --public --token $ZEIT_TOKEN --local-config .now/now.dev.json
                        now --token $ZEIT_TOKEN --local-config .now/now.dev.json alias
                    else
                        ./.now/now.feature.sh
                        now --public --token $ZEIT_TOKEN --local-config .now/now.feature.json
                        now --token $ZEIT_TOKEN --local-config .now/now.feature.json alias
                    fi
workflows:
    version: 2
    test-deploy-purge:
        jobs:
            - checkout
            - unit-test:
                requires:
                    - checkout
            - deploy:
                requires:
                    - unit-test
